travis:
  secure:
    BINSTAR_TOKEN: xcaV0OtaFyIzd/a5Cr+n3MGkj7KrYhA5mb+wWRLAYZO4+ROuIIWd80Uc+suE/de+HN6ODkUoh4pQaxlF7rderSAfPDgNUHgKJh36QIJz42IhZ+cLgXEYiZsg7q+BZuOsGblCvjkIA2cYznQNFfzO8uRDG/NdxKsqDUh3JAZxo5x26jML30FIBjnhVw1hEA3h54cIp29dvGrgaA69a85wDb9U1tOz2GAqX/wT0bTH0n5C1hNXXsn3t6zmDd11AEZGNhsugbTTTWn6GFYZV0RuP3AQ4J1EC2zX8U7J5cIOvivKXcjxnGnrE8eF4YYrsX4OnZgtfeVuFxaWRI3stdUoqa2Gf2cha2DrZT+68saffwE64PTdgxLvYUHOed1to4c5g2YvLPbtM6HWTQ2l4z9xvw5cnx7XGwZZe06OJ0FnCnOIjeJFNBgC4SRSp/wkr8+WosKY0i5HahRniQov0nd/SGCTm5TbGQkUZylmjcHMX5iFWXaW0f+dI9gI8AWmhQi6oXxt7uQLd3NAedZx8rp4HDn60JoFaiynb28YylhQ+uZyWJE+rOiGsDTSe589Ms1xf4/6OgmuHartrPLveypxWzmVngCOLKXFN/QtvUzONmcsdjso8qK6rrBVihgIuQXElNB8QsFxDq/Hm95hE+pcXM+usZBJ8kvwgmjgz8ghsD4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
